// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJNmL_7jUMFRdmPJXgm2-S0GDYX7a_WD4',
    appId: '1:726037551154:web:ff33198592a4bc1851c42b',
    messagingSenderId: '726037551154',
    projectId: 'pidiread',
    authDomain: 'pidiread.firebaseapp.com',
    storageBucket: 'pidiread.firebasestorage.app',
    measurementId: 'G-DQMPHBZY2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu65qZGPl74NAWLLD-mL2bxrp07fhsHp0',
    appId: '1:726037551154:android:19112daaa1b6899b51c42b',
    messagingSenderId: '726037551154',
    projectId: 'pidiread',
    storageBucket: 'pidiread.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb8TmPAjbl8FewDF5Zj9gw1F5rA-F7g1w',
    appId: '1:726037551154:ios:62510267b817073351c42b',
    messagingSenderId: '726037551154',
    projectId: 'pidiread',
    storageBucket: 'pidiread.firebasestorage.app',
    iosBundleId: 'com.example.pidiread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb8TmPAjbl8FewDF5Zj9gw1F5rA-F7g1w',
    appId: '1:726037551154:ios:62510267b817073351c42b',
    messagingSenderId: '726037551154',
    projectId: 'pidiread',
    storageBucket: 'pidiread.firebasestorage.app',
    iosBundleId: 'com.example.pidiread',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJNmL_7jUMFRdmPJXgm2-S0GDYX7a_WD4',
    appId: '1:726037551154:web:f5f53ef8e5bf4cab51c42b',
    messagingSenderId: '726037551154',
    projectId: 'pidiread',
    authDomain: 'pidiread.firebaseapp.com',
    storageBucket: 'pidiread.firebasestorage.app',
    measurementId: 'G-E6WFS3J0WQ',
  );
}
