import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'screens/registration_screen.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'screens/home_screen.dart';
import 'screens/login_screen.dart'; // Import your login screen
import 'screens/profile_screen.dart'; // Import your profile screen
import 'screens/about_screen.dart';
import 'screens/contact_screen.dart';
import 'screens/faq_screen.dart';
import 'screens/privacy_screen.dart';
import 'package:firebase_app_check/firebase_app_check.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await FirebaseAppCheck.instance.activate();
  runApp(const PidiReadApp());
}

class PidiReadApp extends StatelessWidget {
  const PidiReadApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PidiRead',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      initialRoute: '/login', // Set initial route based on auth state
      routes: {
        '/login': (context) => const LoginScreen(), // Define login route
        '/register': (context) => const RegistrationScreen(), //Add this line
        '/home': (context) => const HomeScreen(),
        '/profile': (context) => const ProfileScreen(),
        '/about': (context) => const AboutScreen(),
        '/contact': (context) => const ContactScreen(),
        '/faq': (context) => const FAQScreen(),
        '/privacy': (context) => const PrivacyScreen(),
      },
    );
  }
}